# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from ras_carla/RasObject.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import derived_object_msgs.msg
import shape_msgs.msg
import std_msgs.msg

class RasObject(genpy.Message):
  _md5sum = "6890397792f930487f9106664fc3bee3"
  _type = "ras_carla/RasObject"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """derived_object_msgs/Object object
float32 distance
float32 shift_x
float32 shift_y
bool is_front
float32 importance

================================================================================
MSG: derived_object_msgs/Object
# This represents a detected or tracked object with reference coordinate frame and timestamp.

Header header

# The id of the object (presumably from the detecting sensor).
uint32 id

# A Detected object is one which has been seen in at least one scan/frame of a sensor.
# A Tracked object is one which has been correlated over multiple scans/frames of a sensor.
# An object which is detected can only be assumed to have valid pose and shape properties.
# An object which is tracked should also be assumed to have valid twist and accel properties.
uint8 detection_level

uint8 OBJECT_DETECTED=0
uint8 OBJECT_TRACKED=1

# A Classified object is one which has been identified as a certain object type.
# Classified objects should have valid classification, classification_certainty, and classification_age properties.
bool object_classified

# The detected position and orientation of the object.
geometry_msgs/Pose pose

# The detected linear and angular velocities of the object.
geometry_msgs/Twist twist

# The detected linear and angular accelerations of the object.
geometry_msgs/Accel accel

# (OPTIONAL) The polygon defining the detection points at the outer edges of the object.
geometry_msgs/Polygon polygon

# A shape conforming to the outer bounding edges of the object.
shape_msgs/SolidPrimitive shape

# The type of classification given to this object.
uint8 classification

uint8 CLASSIFICATION_UNKNOWN=0
uint8 CLASSIFICATION_UNKNOWN_SMALL=1
uint8 CLASSIFICATION_UNKNOWN_MEDIUM=2
uint8 CLASSIFICATION_UNKNOWN_BIG=3
uint8 CLASSIFICATION_PEDESTRIAN=4
uint8 CLASSIFICATION_BIKE=5
uint8 CLASSIFICATION_CAR=6
uint8 CLASSIFICATION_TRUCK=7
uint8 CLASSIFICATION_MOTORCYCLE=8
uint8 CLASSIFICATION_OTHER_VEHICLE=9
uint8 CLASSIFICATION_BARRIER=10
uint8 CLASSIFICATION_SIGN=11

# The certainty of the classification from the originating sensor.
# Higher value indicates greater certainty (MAX=255).
# It is recommended that a native sensor value be scaled to 0-255 for interoperability.
uint8 classification_certainty

# The number of scans/frames from the sensor that this object has been classified as the current classification.
uint32 classification_age

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id

================================================================================
MSG: geometry_msgs/Pose
# A representation of pose in free space, composed of position and orientation. 
Point position
Quaternion orientation

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w

================================================================================
MSG: geometry_msgs/Twist
# This expresses velocity in free space broken into its linear and angular parts.
Vector3  linear
Vector3  angular

================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 
# It is only meant to represent a direction. Therefore, it does not
# make sense to apply a translation to it (e.g., when applying a 
# generic rigid transformation to a Vector3, tf2 will only apply the
# rotation). If you want your data to be translatable too, use the
# geometry_msgs/Point message instead.

float64 x
float64 y
float64 z
================================================================================
MSG: geometry_msgs/Accel
# This expresses acceleration in free space broken into its linear and angular parts.
Vector3  linear
Vector3  angular

================================================================================
MSG: geometry_msgs/Polygon
#A specification of a polygon where the first and last points are assumed to be connected
Point32[] points

================================================================================
MSG: geometry_msgs/Point32
# This contains the position of a point in free space(with 32 bits of precision).
# It is recommeded to use Point wherever possible instead of Point32.  
# 
# This recommendation is to promote interoperability.  
#
# This message is designed to take up less space when sending
# lots of points at once, as in the case of a PointCloud.  

float32 x
float32 y
float32 z
================================================================================
MSG: shape_msgs/SolidPrimitive
# Define box, sphere, cylinder, cone 
# All shapes are defined to have their bounding boxes centered around 0,0,0.

uint8 BOX=1
uint8 SPHERE=2
uint8 CYLINDER=3
uint8 CONE=4

# The type of the shape
uint8 type


# The dimensions of the shape
float64[] dimensions

# The meaning of the shape dimensions: each constant defines the index in the 'dimensions' array

# For the BOX type, the X, Y, and Z dimensions are the length of the corresponding
# sides of the box.
uint8 BOX_X=0
uint8 BOX_Y=1
uint8 BOX_Z=2


# For the SPHERE type, only one component is used, and it gives the radius of
# the sphere.
uint8 SPHERE_RADIUS=0


# For the CYLINDER and CONE types, the center line is oriented along
# the Z axis.  Therefore the CYLINDER_HEIGHT (CONE_HEIGHT) component
# of dimensions gives the height of the cylinder (cone).  The
# CYLINDER_RADIUS (CONE_RADIUS) component of dimensions gives the
# radius of the base of the cylinder (cone).  Cone and cylinder
# primitives are defined to be circular. The tip of the cone is
# pointing up, along +Z axis.

uint8 CYLINDER_HEIGHT=0
uint8 CYLINDER_RADIUS=1

uint8 CONE_HEIGHT=0
uint8 CONE_RADIUS=1
"""
  __slots__ = ['object','distance','shift_x','shift_y','is_front','importance']
  _slot_types = ['derived_object_msgs/Object','float32','float32','float32','bool','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       object,distance,shift_x,shift_y,is_front,importance

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(RasObject, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.object is None:
        self.object = derived_object_msgs.msg.Object()
      if self.distance is None:
        self.distance = 0.
      if self.shift_x is None:
        self.shift_x = 0.
      if self.shift_y is None:
        self.shift_y = 0.
      if self.is_front is None:
        self.is_front = False
      if self.importance is None:
        self.importance = 0.
    else:
      self.object = derived_object_msgs.msg.Object()
      self.distance = 0.
      self.shift_x = 0.
      self.shift_y = 0.
      self.is_front = False
      self.importance = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.object.header.seq, _x.object.header.stamp.secs, _x.object.header.stamp.nsecs))
      _x = self.object.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_I2B19d().pack(_x.object.id, _x.object.detection_level, _x.object.object_classified, _x.object.pose.position.x, _x.object.pose.position.y, _x.object.pose.position.z, _x.object.pose.orientation.x, _x.object.pose.orientation.y, _x.object.pose.orientation.z, _x.object.pose.orientation.w, _x.object.twist.linear.x, _x.object.twist.linear.y, _x.object.twist.linear.z, _x.object.twist.angular.x, _x.object.twist.angular.y, _x.object.twist.angular.z, _x.object.accel.linear.x, _x.object.accel.linear.y, _x.object.accel.linear.z, _x.object.accel.angular.x, _x.object.accel.angular.y, _x.object.accel.angular.z))
      length = len(self.object.polygon.points)
      buff.write(_struct_I.pack(length))
      for val1 in self.object.polygon.points:
        _x = val1
        buff.write(_get_struct_3f().pack(_x.x, _x.y, _x.z))
      buff.write(_get_struct_B().pack(self.object.shape.type))
      length = len(self.object.shape.dimensions)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.pack(pattern, *self.object.shape.dimensions))
      _x = self
      buff.write(_get_struct_2BI3fBf().pack(_x.object.classification, _x.object.classification_certainty, _x.object.classification_age, _x.distance, _x.shift_x, _x.shift_y, _x.is_front, _x.importance))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.object is None:
        self.object = derived_object_msgs.msg.Object()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.object.header.seq, _x.object.header.stamp.secs, _x.object.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.object.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.object.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 158
      (_x.object.id, _x.object.detection_level, _x.object.object_classified, _x.object.pose.position.x, _x.object.pose.position.y, _x.object.pose.position.z, _x.object.pose.orientation.x, _x.object.pose.orientation.y, _x.object.pose.orientation.z, _x.object.pose.orientation.w, _x.object.twist.linear.x, _x.object.twist.linear.y, _x.object.twist.linear.z, _x.object.twist.angular.x, _x.object.twist.angular.y, _x.object.twist.angular.z, _x.object.accel.linear.x, _x.object.accel.linear.y, _x.object.accel.linear.z, _x.object.accel.angular.x, _x.object.accel.angular.y, _x.object.accel.angular.z,) = _get_struct_I2B19d().unpack(str[start:end])
      self.object.object_classified = bool(self.object.object_classified)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.object.polygon.points = []
      for i in range(0, length):
        val1 = geometry_msgs.msg.Point32()
        _x = val1
        start = end
        end += 12
        (_x.x, _x.y, _x.z,) = _get_struct_3f().unpack(str[start:end])
        self.object.polygon.points.append(val1)
      start = end
      end += 1
      (self.object.shape.type,) = _get_struct_B().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.object.shape.dimensions = struct.unpack(pattern, str[start:end])
      _x = self
      start = end
      end += 23
      (_x.object.classification, _x.object.classification_certainty, _x.object.classification_age, _x.distance, _x.shift_x, _x.shift_y, _x.is_front, _x.importance,) = _get_struct_2BI3fBf().unpack(str[start:end])
      self.is_front = bool(self.is_front)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.object.header.seq, _x.object.header.stamp.secs, _x.object.header.stamp.nsecs))
      _x = self.object.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_I2B19d().pack(_x.object.id, _x.object.detection_level, _x.object.object_classified, _x.object.pose.position.x, _x.object.pose.position.y, _x.object.pose.position.z, _x.object.pose.orientation.x, _x.object.pose.orientation.y, _x.object.pose.orientation.z, _x.object.pose.orientation.w, _x.object.twist.linear.x, _x.object.twist.linear.y, _x.object.twist.linear.z, _x.object.twist.angular.x, _x.object.twist.angular.y, _x.object.twist.angular.z, _x.object.accel.linear.x, _x.object.accel.linear.y, _x.object.accel.linear.z, _x.object.accel.angular.x, _x.object.accel.angular.y, _x.object.accel.angular.z))
      length = len(self.object.polygon.points)
      buff.write(_struct_I.pack(length))
      for val1 in self.object.polygon.points:
        _x = val1
        buff.write(_get_struct_3f().pack(_x.x, _x.y, _x.z))
      buff.write(_get_struct_B().pack(self.object.shape.type))
      length = len(self.object.shape.dimensions)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.object.shape.dimensions.tostring())
      _x = self
      buff.write(_get_struct_2BI3fBf().pack(_x.object.classification, _x.object.classification_certainty, _x.object.classification_age, _x.distance, _x.shift_x, _x.shift_y, _x.is_front, _x.importance))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.object is None:
        self.object = derived_object_msgs.msg.Object()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.object.header.seq, _x.object.header.stamp.secs, _x.object.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.object.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.object.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 158
      (_x.object.id, _x.object.detection_level, _x.object.object_classified, _x.object.pose.position.x, _x.object.pose.position.y, _x.object.pose.position.z, _x.object.pose.orientation.x, _x.object.pose.orientation.y, _x.object.pose.orientation.z, _x.object.pose.orientation.w, _x.object.twist.linear.x, _x.object.twist.linear.y, _x.object.twist.linear.z, _x.object.twist.angular.x, _x.object.twist.angular.y, _x.object.twist.angular.z, _x.object.accel.linear.x, _x.object.accel.linear.y, _x.object.accel.linear.z, _x.object.accel.angular.x, _x.object.accel.angular.y, _x.object.accel.angular.z,) = _get_struct_I2B19d().unpack(str[start:end])
      self.object.object_classified = bool(self.object.object_classified)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.object.polygon.points = []
      for i in range(0, length):
        val1 = geometry_msgs.msg.Point32()
        _x = val1
        start = end
        end += 12
        (_x.x, _x.y, _x.z,) = _get_struct_3f().unpack(str[start:end])
        self.object.polygon.points.append(val1)
      start = end
      end += 1
      (self.object.shape.type,) = _get_struct_B().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.object.shape.dimensions = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      _x = self
      start = end
      end += 23
      (_x.object.classification, _x.object.classification_certainty, _x.object.classification_age, _x.distance, _x.shift_x, _x.shift_y, _x.is_front, _x.importance,) = _get_struct_2BI3fBf().unpack(str[start:end])
      self.is_front = bool(self.is_front)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2BI3fBf = None
def _get_struct_2BI3fBf():
    global _struct_2BI3fBf
    if _struct_2BI3fBf is None:
        _struct_2BI3fBf = struct.Struct("<2BI3fBf")
    return _struct_2BI3fBf
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_B = None
def _get_struct_B():
    global _struct_B
    if _struct_B is None:
        _struct_B = struct.Struct("<B")
    return _struct_B
_struct_3f = None
def _get_struct_3f():
    global _struct_3f
    if _struct_3f is None:
        _struct_3f = struct.Struct("<3f")
    return _struct_3f
_struct_I2B19d = None
def _get_struct_I2B19d():
    global _struct_I2B19d
    if _struct_I2B19d is None:
        _struct_I2B19d = struct.Struct("<I2B19d")
    return _struct_I2B19d
