// Generated by gencpp from file swipe_obstacles/closest_obstacle.msg
// DO NOT EDIT!


#ifndef SWIPE_OBSTACLES_MESSAGE_CLOSEST_OBSTACLE_H
#define SWIPE_OBSTACLES_MESSAGE_CLOSEST_OBSTACLE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace swipe_obstacles
{
template <class ContainerAllocator>
struct closest_obstacle_
{
  typedef closest_obstacle_<ContainerAllocator> Type;

  closest_obstacle_()
    : header()
    , id(0)
    , distance(0.0)
    , brief_stop(0)
    , stop_time(0.0)
    , stop_distance(0.0)  {
    }
  closest_obstacle_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , id(0)
    , distance(0.0)
    , brief_stop(0)
    , stop_time(0.0)
    , stop_distance(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint32_t _id_type;
  _id_type id;

   typedef float _distance_type;
  _distance_type distance;

   typedef uint32_t _brief_stop_type;
  _brief_stop_type brief_stop;

   typedef float _stop_time_type;
  _stop_time_type stop_time;

   typedef float _stop_distance_type;
  _stop_distance_type stop_distance;





  typedef boost::shared_ptr< ::swipe_obstacles::closest_obstacle_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::swipe_obstacles::closest_obstacle_<ContainerAllocator> const> ConstPtr;

}; // struct closest_obstacle_

typedef ::swipe_obstacles::closest_obstacle_<std::allocator<void> > closest_obstacle;

typedef boost::shared_ptr< ::swipe_obstacles::closest_obstacle > closest_obstaclePtr;
typedef boost::shared_ptr< ::swipe_obstacles::closest_obstacle const> closest_obstacleConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::swipe_obstacles::closest_obstacle_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::swipe_obstacles::closest_obstacle_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace swipe_obstacles

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'swipe_obstacles': ['/home/mad-autoware/catkin_ws/src/swipe_obstacles/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::swipe_obstacles::closest_obstacle_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::swipe_obstacles::closest_obstacle_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::swipe_obstacles::closest_obstacle_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::swipe_obstacles::closest_obstacle_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::swipe_obstacles::closest_obstacle_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::swipe_obstacles::closest_obstacle_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::swipe_obstacles::closest_obstacle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f82492c5a8a267aeb81808dbb76fd96b";
  }

  static const char* value(const ::swipe_obstacles::closest_obstacle_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf82492c5a8a267aeULL;
  static const uint64_t static_value2 = 0xb81808dbb76fd96bULL;
};

template<class ContainerAllocator>
struct DataType< ::swipe_obstacles::closest_obstacle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "swipe_obstacles/closest_obstacle";
  }

  static const char* value(const ::swipe_obstacles::closest_obstacle_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::swipe_obstacles::closest_obstacle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n\
\n\
uint32 id\n\
float32 distance\n\
uint32 brief_stop\n\
float32 stop_time\n\
float32 stop_distance\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::swipe_obstacles::closest_obstacle_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::swipe_obstacles::closest_obstacle_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.id);
      stream.next(m.distance);
      stream.next(m.brief_stop);
      stream.next(m.stop_time);
      stream.next(m.stop_distance);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct closest_obstacle_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::swipe_obstacles::closest_obstacle_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::swipe_obstacles::closest_obstacle_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "id: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.id);
    s << indent << "distance: ";
    Printer<float>::stream(s, indent + "  ", v.distance);
    s << indent << "brief_stop: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.brief_stop);
    s << indent << "stop_time: ";
    Printer<float>::stream(s, indent + "  ", v.stop_time);
    s << indent << "stop_distance: ";
    Printer<float>::stream(s, indent + "  ", v.stop_distance);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SWIPE_OBSTACLES_MESSAGE_CLOSEST_OBSTACLE_H
